<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" > 
    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_width" value="0.1" />
    <xacro:property name="camera_height" value="0.05" />
    <xacro:property name="camera_mass" value="0.1" />

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>     
        <xacro:box_inertia m="${camera_mass}" l="${camera_length}" w="${camera_width}" 
        h="${camera_height}" xyz="0 0 0" rpy="0 0 0" />

    </link>

    <joint name="base_camera_link" type="fixed" >
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${(base_length + camera_length) / 2} 0 ${base_height / 2}" rpy="0 0 0" />
    </joint>

    <gazebo reference="camera_link">
        <material>Gazebo/Green</material>
        <sensor name="camera_sensor" type="camera">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>20.0</update_rate>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>
</robot>